package com.example.test.pojo;

public class AudioBank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audio_bank.id
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audio_bank.type
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audio_bank.audio_name
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private String audio_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audio_bank.audio_content
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private String audio_content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audio_bank.id
     *
     * @return the value of audio_bank.id
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audio_bank.id
     *
     * @param id the value for audio_bank.id
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audio_bank.type
     *
     * @return the value of audio_bank.type
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audio_bank.type
     *
     * @param type the value for audio_bank.type
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audio_bank.audio_name
     *
     * @return the value of audio_bank.audio_name
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public String getAudio_name() {
        return audio_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audio_bank.audio_name
     *
     * @param audio_name the value for audio_bank.audio_name
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setAudio_name(String audio_name) {
        this.audio_name = audio_name == null ? null : audio_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audio_bank.audio_content
     *
     * @return the value of audio_bank.audio_content
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public String getAudio_content() {
        return audio_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audio_bank.audio_content
     *
     * @param audio_content the value for audio_bank.audio_content
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setAudio_content(String audio_content) {
        this.audio_content = audio_content;
    }
}