package com.example.test.pojo;

public class Composition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composition.idcomposition
     *
     * @mbg.generated Thu Mar 02 10:40:26 CST 2023
     */
    private Integer idcomposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composition.content
     *
     * @mbg.generated Thu Mar 02 10:40:26 CST 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composition.idcomposition
     *
     * @return the value of composition.idcomposition
     *
     * @mbg.generated Thu Mar 02 10:40:26 CST 2023
     */
    public Integer getIdcomposition() {
        return idcomposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composition.idcomposition
     *
     * @param idcomposition the value for composition.idcomposition
     *
     * @mbg.generated Thu Mar 02 10:40:26 CST 2023
     */
    public void setIdcomposition(Integer idcomposition) {
        this.idcomposition = idcomposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composition.content
     *
     * @return the value of composition.content
     *
     * @mbg.generated Thu Mar 02 10:40:26 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composition.content
     *
     * @param content the value for composition.content
     *
     * @mbg.generated Thu Mar 02 10:40:26 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}