package com.example.test.pojo;

public class FriendRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_request.requestId
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    private Integer requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_request.promoter
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    private String promoter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_request.receiver
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_request.state
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_request.requestId
     *
     * @return the value of friend_request.requestId
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_request.requestId
     *
     * @param requestId the value for friend_request.requestId
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_request.promoter
     *
     * @return the value of friend_request.promoter
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    public String getPromoter() {
        return promoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_request.promoter
     *
     * @param promoter the value for friend_request.promoter
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    public void setPromoter(String promoter) {
        this.promoter = promoter == null ? null : promoter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_request.receiver
     *
     * @return the value of friend_request.receiver
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_request.receiver
     *
     * @param receiver the value for friend_request.receiver
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_request.state
     *
     * @return the value of friend_request.state
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_request.state
     *
     * @param state the value for friend_request.state
     *
     * @mbg.generated Sat Apr 15 12:52:19 CST 2023
     */
    public void setState(Integer state) {
        this.state = state;
    }
}