package com.example.test.pojo;

public class Hsk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsk.idhsk
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    private String idhsk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsk.level
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsk.content
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsk.answer
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    private String answer;

    private String audio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsk.idhsk
     *
     * @return the value of hsk.idhsk
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    public String getIdhsk() {
        return idhsk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsk.idhsk
     *
     * @param idhsk the value for hsk.idhsk
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    public void setIdhsk(String idhsk) {
        this.idhsk = idhsk == null ? null : idhsk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsk.level
     *
     * @return the value of hsk.level
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsk.level
     *
     * @param level the value for hsk.level
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsk.content
     *
     * @return the value of hsk.content
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsk.content
     *
     * @param content the value for hsk.content
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsk.answer
     *
     * @return the value of hsk.answer
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsk.answer
     *
     * @param answer the value for hsk.answer
     *
     * @mbg.generated Wed Feb 15 09:09:15 CST 2023
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getAudio() {
        return audio;
    }

    public void setAudio(String audio) {
        this.audio = audio;
    }
}