package com.example.test.pojo;

public class ListeningQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_question.id
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_question.type
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_question.content
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_question.option1
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private String option1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_question.option2
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private String option2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_question.option3
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private String option3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_question.option4
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private String option4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_question.audio_id
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private Integer audio_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_question.answer
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_question.id
     *
     * @return the value of listening_question.id
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_question.id
     *
     * @param id the value for listening_question.id
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_question.type
     *
     * @return the value of listening_question.type
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_question.type
     *
     * @param type the value for listening_question.type
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_question.content
     *
     * @return the value of listening_question.content
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_question.content
     *
     * @param content the value for listening_question.content
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_question.option1
     *
     * @return the value of listening_question.option1
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public String getOption1() {
        return option1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_question.option1
     *
     * @param option1 the value for listening_question.option1
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setOption1(String option1) {
        this.option1 = option1 == null ? null : option1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_question.option2
     *
     * @return the value of listening_question.option2
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public String getOption2() {
        return option2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_question.option2
     *
     * @param option2 the value for listening_question.option2
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setOption2(String option2) {
        this.option2 = option2 == null ? null : option2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_question.option3
     *
     * @return the value of listening_question.option3
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public String getOption3() {
        return option3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_question.option3
     *
     * @param option3 the value for listening_question.option3
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setOption3(String option3) {
        this.option3 = option3 == null ? null : option3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_question.option4
     *
     * @return the value of listening_question.option4
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public String getOption4() {
        return option4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_question.option4
     *
     * @param option4 the value for listening_question.option4
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setOption4(String option4) {
        this.option4 = option4 == null ? null : option4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_question.audio_id
     *
     * @return the value of listening_question.audio_id
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public Integer getAudio_id() {
        return audio_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_question.audio_id
     *
     * @param audio_id the value for listening_question.audio_id
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setAudio_id(Integer audio_id) {
        this.audio_id = audio_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_question.answer
     *
     * @return the value of listening_question.answer
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_question.answer
     *
     * @param answer the value for listening_question.answer
     *
     * @mbg.generated Sat Jan 14 11:27:56 CST 2023
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}