package com.example.test.pojo;

public class PictureBank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_bank.id
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_bank.type
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_bank.picture_name
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    private String picture_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_bank.picture_content
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    private String picture_content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_bank.id
     *
     * @return the value of picture_bank.id
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_bank.id
     *
     * @param id the value for picture_bank.id
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_bank.type
     *
     * @return the value of picture_bank.type
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_bank.type
     *
     * @param type the value for picture_bank.type
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_bank.picture_name
     *
     * @return the value of picture_bank.picture_name
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    public String getPicture_name() {
        return picture_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_bank.picture_name
     *
     * @param picture_name the value for picture_bank.picture_name
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    public void setPicture_name(String picture_name) {
        this.picture_name = picture_name == null ? null : picture_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_bank.picture_content
     *
     * @return the value of picture_bank.picture_content
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    public String getPicture_content() {
        return picture_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_bank.picture_content
     *
     * @param picture_content the value for picture_bank.picture_content
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    public void setPicture_content(String picture_content) {
        this.picture_content = picture_content;
    }
}