package com.example.test.pojo;

public class Quiz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.id
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.type
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.content
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.optiona
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    private String optiona;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.optionb
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    private String optionb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.optionc
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    private String optionc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.optiond
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    private String optiond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.answer
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.level
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.id
     *
     * @return the value of quiz.id
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.id
     *
     * @param id the value for quiz.id
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.type
     *
     * @return the value of quiz.type
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.type
     *
     * @param type the value for quiz.type
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.content
     *
     * @return the value of quiz.content
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.content
     *
     * @param content the value for quiz.content
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.optiona
     *
     * @return the value of quiz.optiona
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public String getOptiona() {
        return optiona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.optiona
     *
     * @param optiona the value for quiz.optiona
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public void setOptiona(String optiona) {
        this.optiona = optiona == null ? null : optiona.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.optionb
     *
     * @return the value of quiz.optionb
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public String getOptionb() {
        return optionb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.optionb
     *
     * @param optionb the value for quiz.optionb
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public void setOptionb(String optionb) {
        this.optionb = optionb == null ? null : optionb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.optionc
     *
     * @return the value of quiz.optionc
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public String getOptionc() {
        return optionc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.optionc
     *
     * @param optionc the value for quiz.optionc
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public void setOptionc(String optionc) {
        this.optionc = optionc == null ? null : optionc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.optiond
     *
     * @return the value of quiz.optiond
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public String getOptiond() {
        return optiond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.optiond
     *
     * @param optiond the value for quiz.optiond
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public void setOptiond(String optiond) {
        this.optiond = optiond == null ? null : optiond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.answer
     *
     * @return the value of quiz.answer
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.answer
     *
     * @param answer the value for quiz.answer
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.level
     *
     * @return the value of quiz.level
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.level
     *
     * @param level the value for quiz.level
     *
     * @mbg.generated Thu Mar 02 10:37:07 CST 2023
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }
}