package com.example.test.pojo;

public class Stack {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stack.chaptername
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    private String chaptername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stack.bookname
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    private String bookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stack.content
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stack.pinyin
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    private String pinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stack.level
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stack.chaptername
     *
     * @return the value of stack.chaptername
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public String getChaptername() {
        return chaptername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stack.chaptername
     *
     * @param chaptername the value for stack.chaptername
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public void setChaptername(String chaptername) {
        this.chaptername = chaptername == null ? null : chaptername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stack.bookname
     *
     * @return the value of stack.bookname
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stack.bookname
     *
     * @param bookname the value for stack.bookname
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stack.content
     *
     * @return the value of stack.content
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stack.content
     *
     * @param content the value for stack.content
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stack.pinyin
     *
     * @return the value of stack.pinyin
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stack.pinyin
     *
     * @param pinyin the value for stack.pinyin
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stack.level
     *
     * @return the value of stack.level
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stack.level
     *
     * @param level the value for stack.level
     *
     * @mbg.generated Tue Feb 28 10:15:10 CST 2023
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }
}