package com.example.test.pojo;

public class Word {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.idword
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    private Integer idword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.content
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.level
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.idword
     *
     * @return the value of word.idword
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    public Integer getIdword() {
        return idword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.idword
     *
     * @param idword the value for word.idword
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    public void setIdword(Integer idword) {
        this.idword = idword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.content
     *
     * @return the value of word.content
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.content
     *
     * @param content the value for word.content
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.level
     *
     * @return the value of word.level
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.level
     *
     * @param level the value for word.level
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }
}